FROM registry.redhat.io/rhel9-eus/rhel-9.6-bootc:9.6

# Install microshift
ARG USHIFT_VER=4.18
# hadolint ignore=SC1091
RUN . /etc/os-release && dnf upgrade -y --releasever="${VERSION_ID}" && \
    dnf config-manager \
        --set-enabled "rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms" \
        --set-enabled "fast-datapath-for-rhel-9-$(uname -m)-rpms" && \
    dnf install -y firewalld jq microshift microshift-release-info && \
    systemctl enable microshift && \
    dnf clean all

# Ensure path exists
RUN mkdir -p /etc/crio

# Add your pull secret and lock it down
COPY pull-secret.json /etc/crio/openshift-pull-secret
RUN chmod 600 /etc/crio/openshift-pull-secret

# Set selinux to permissive mode
RUN sudo sed -i 's/^SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
