apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: demo-device-fleet-01
spec:
  selector:
    matchLabels:
      env: kiosk
      provider: git
  template:
    metadata:
      labels:
        fleet: git-demo-fleet
    spec:
      applications: []
      config: 
        - name: kiosk-content
          gitRef:
            path: /kiosk/content
            repository: student1-content
            targetRevision: main
      os:
        image: quay.io/kenosborn/drone-image:v1
