[customizations.installer.kickstart]
contents = """

# Unnatended install
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text --non-interactive
rootpw --lock
reboot

# Configure disk
zerombr
clearpart --all --initlabel
reqpart --add-boot

# Configure network
network --bootproto=dhcp --device=link --activate --onboot=on

%post --log=/var/log/anaconda/post-install.log --erroronfail

# Local user for console login and SSH
useradd -g wheel redhat
echo "redhat:redhat123" | chpasswd
mkdir /home/redhat/.ssh


# Set a hostname, just for convenience
# echo "ushift" > /etc/hostname
# chmod 644 /etc/hostname

%end
"""

