apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: demo-device-fleet-01
spec:
  selector:
    matchLabels:
      env: demo-01
  template:
    metadata:
      labels:
        fleet: demo-device-fleet-01
    spec:
      applications: []
      config:
      - gitRef:
          mountPath: /etc/
          path: /etc/
          repository: demo-repository-01
          targetRevision: main
        name: motd
      os:
        image: quay.io/kenosborn/rhem0.7.2-edge-device-base:v1
