apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: test-fleet
spec:
  selector:
    matchLabels:
      fleet: test
  template:
    metadata:
      labels:
        fleet: test-fleet
    spec:
      applications: []
      config:
        - name: motd-update
          inline:
            - path: /etc/motd
              content: |+
                Hello from our Demo!!
      os:
        image: quay.io/kenosborn/drone-image:v1
