apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  labels: {}
  name: test-fleet
spec:
  selector:
    matchLabels:
      fleet: test
  template:
    metadata:
      labels:
        fleet: test-fleet
    spec:
      applications: []
      config: []
      os:
        image: quay.io/kenosborn/drone-image:v1
