apiVersion: flightctl.io/v1beta1
kind: Fleet
metadata:
  labels: {}
  name: git-fleet
spec:
  selector:
    matchLabels:
      fleet: git
  template:
    metadata:
      labels:
        fleet: git-fleet
    spec:
      applications: []
      config: []
      os:
        image: quay.io/user/drone-image:v1
