[customizations.installer.kickstart]
contents = """

# Unnatended install
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text --non-interactive
rootpw --lock
reboot

# leave free space on the "redhat" VG for the LVM Storate operator
zerombr
clearpart --all --initlabel
part /boot/efi --fstype=efi --size=200
part /boot --fstype=xfs --asprimary --size=800
part pv.01 --grow
volgroup rhel pv.01
logvol / --vgname=rhel --fstype=xfs --size=10240 --name=root

network --bootproto=dhcp --device=link --activate --onboot=on

%post --log=/var/log/anaconda/post-install.log --erroronfail

# Local user for console login and SSH
useradd -g wheel core
echo "core:redhat123" | chpasswd
mkdir /home/core/.ssh
cat > /home/core/.ssh/authorized_keys << EOF
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLs0yN1u5GBeOaIX4ccwFo+W4xYchfIJ1kI2lxmV3nTnIT3x26z3zJgwiY2TZ+SWiAtwNpqp/B5ZKObqLr3HARKvnDcC5Vr0uqorfoTX/kh+b6CmeCYNoLDSP82XNYPsw0/YAnfc6W3JtkwU3gGW812P5+IPomDUSOta+taM5WB1KAs+xDx5pdoww3INVb/Fvv6Jixpcj876qpyCV40q8FRPJo23dpQGJDMxfIp14K4HhnSjWi6VvwTicsQ5nMw/voQCx8HbAu6tcrk/qKNooRS75kXGTrQ9nQ4MsE3S7dupBAixvsmrgIxC55mynCBH5+1zdA1aWQS8BidHMbDgl6TRbDL0jFjZkS0a20TEzPMeHC44CdcfNFl0D5mFcLLi1hqOLvlR281cM3MfFFnzsORPiGTQ4JNcdE9uz/OSOaYap6BwmYFZN0IDlHVCNHWFmCaub3pp/Kf7H7KKJJfwzxgqDKid4VOGX5YFJxX+j2ObMBoUiAgIBPmG9LeLBBlXb0LkgFi8xCxagRJo+2GbEdmZbrufJBPg33RhCewLikCGqxbxzW7XScqLI3TiqAmIwg+QQ3wOFfnAYRisbaT5eNv9pwoC6CnpGCWVYagpxrJ3aSsyl3oiiV4xUYOzQxf+GUpg62C9QCvP9oP4GS5kXPTRXYr4/bVTwT76NwsHtf8Q== kosborn@redhat.com
EOF

# Need a pull secret to download container images from whatever registries we need (for images are not embedded into the bootc image)
cat > /etc/crio/openshift-pull-secret <<EOF
{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMjg2NGE5MWVlYWI3NGI1NWFmMzIzNmI5MzY2OGFjM2M6RkQ3WEw2M0FTOVhEVFFQWVZMTlI4NlUzTDJDM0FaTTk5VEk2UjZVSU9KSUhPR0dTSDIxR1JMMEc1VUw2RTdDNQ==","email":"kosborn@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMjg2NGE5MWVlYWI3NGI1NWFmMzIzNmI5MzY2OGFjM2M6RkQ3WEw2M0FTOVhEVFFQWVZMTlI4NlUzTDJDM0FaTTk5VEk2UjZVSU9KSUhPR0dTSDIxR1JMMEc1VUw2RTdDNQ==","email":"kosborn@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTUyN2YzODNiLTkwMzEtNGU3NS04ZTM2LWVjMjM5MTUyNTg0NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTVOR1ZqTUdZeU1HVmxORGcwWTJJNE9EaGlPR0poWkRnNE1tWXdPVEF4TnlKOS5CeExSc2lvZjF5SVRCMTUyUlZCSTJtMU1GeWJHUnU3R0k3YllVVk5VOEpKVTlCRENsMjV3MTNNRm9VRFJNVmk1aF82Z2FKSGNZekt2VjNJUkl6MVBTaUZ1YW11MWFfTnVNZlZzNjhldmdIS1NkaTNmdGdwVE1ySkRjU19EdXFEM01yOERlMG83bGdPa1dYRU5RQm9wUV9QTnFxcl8tdUUyRDdaZTRNMVg1eGYwNjRMSGZ1Z1o3VGdJbFp1Vm1ZQmJaMUJFMlppNThqY2NBZWlfMGNsRkx2UUpRbnZ3NkxPRlFld2JSbjF4SUlXRVd5dW1YOHZlUFpzdU13WTBBRlNLZlBzdlgtZkJybWJkYmV2eFpwMFB0X2lIY3dkNDdnY05VVTlqOE9lRHd6TDVYLXk3SmdCalVrZnlLZGFMeS1KUDRmeVFDaldudDE1T204S3BtdThxd1ZvZExaMUFMQmxfdXNTMDIxVWtpSE1Yc05aWWZmaXhFczdrLUNSZUZvM0NxcGhIWkdzbFN1emR0VzI1a2dHTDdhb194U2JvWTUyRmt1eEhlbDBSd0NnTm5mQjhmU2tCTXhUVGZ6dTJBcENsVk9JbkpucHFfUjRwY05HejA1aFVQNkVubkI2TFAtdlUyZnNMbzZIaUxkd204SHlUOEJ3Z3hLa2p4c1JSa2tEa1hUUUdxVFRYTGpSc29jMmZ3RXNQRVJ2VHRReEY1WkZxOGJnWklyLTd2ZWh5RG14U3pvdDVTbXFRQWhjdGtIT2ZrX0FsbmVQU0dHd0tzVlhteU85Z2ZBTXBmaGZEVHRreU9JM0xTZVlYVUNXRWxUNlFUR1pELVRsRVIzRGFXWWpfTDhMZ3E1eXZmT25qTzE2OVVwUWNpQjE4MFl5WnpWaEwyLVBmVG5UYjlvYw==","email":"kosborn@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTUyN2YzODNiLTkwMzEtNGU3NS04ZTM2LWVjMjM5MTUyNTg0NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTVOR1ZqTUdZeU1HVmxORGcwWTJJNE9EaGlPR0poWkRnNE1tWXdPVEF4TnlKOS5CeExSc2lvZjF5SVRCMTUyUlZCSTJtMU1GeWJHUnU3R0k3YllVVk5VOEpKVTlCRENsMjV3MTNNRm9VRFJNVmk1aF82Z2FKSGNZekt2VjNJUkl6MVBTaUZ1YW11MWFfTnVNZlZzNjhldmdIS1NkaTNmdGdwVE1ySkRjU19EdXFEM01yOERlMG83bGdPa1dYRU5RQm9wUV9QTnFxcl8tdUUyRDdaZTRNMVg1eGYwNjRMSGZ1Z1o3VGdJbFp1Vm1ZQmJaMUJFMlppNThqY2NBZWlfMGNsRkx2UUpRbnZ3NkxPRlFld2JSbjF4SUlXRVd5dW1YOHZlUFpzdU13WTBBRlNLZlBzdlgtZkJybWJkYmV2eFpwMFB0X2lIY3dkNDdnY05VVTlqOE9lRHd6TDVYLXk3SmdCalVrZnlLZGFMeS1KUDRmeVFDaldudDE1T204S3BtdThxd1ZvZExaMUFMQmxfdXNTMDIxVWtpSE1Yc05aWWZmaXhFczdrLUNSZUZvM0NxcGhIWkdzbFN1emR0VzI1a2dHTDdhb194U2JvWTUyRmt1eEhlbDBSd0NnTm5mQjhmU2tCTXhUVGZ6dTJBcENsVk9JbkpucHFfUjRwY05HejA1aFVQNkVubkI2TFAtdlUyZnNMbzZIaUxkd204SHlUOEJ3Z3hLa2p4c1JSa2tEa1hUUUdxVFRYTGpSc29jMmZ3RXNQRVJ2VHRReEY1WkZxOGJnWklyLTd2ZWh5RG14U3pvdDVTbXFRQWhjdGtIT2ZrX0FsbmVQU0dHd0tzVlhteU85Z2ZBTXBmaGZEVHRreU9JM0xTZVlYVUNXRWxUNlFUR1pELVRsRVIzRGFXWWpfTDhMZ3E1eXZmT25qTzE2OVVwUWNpQjE4MFl5WnpWaEwyLVBmVG5UYjlvYw==","email":"kosborn@redhat.com"}}}
EOF
chmod 600 /etc/crio/openshift-pull-secret

# Set a hostname, just for convenience
#echo "ushift" > /etc/hostname
#chmod 644 /etc/hostname

%end
"""
