FROM registry.redhat.io/rhel9-eus/rhel-9.6-bootc:9.6

# Install Edge Manager Agent  
RUN dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf -y clean all && \
    dnf -y install flightctl-agent-0:1.0.0-1.el9.x86_64 && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Set root password - WORKSHOP PURPOSES ONLY
RUN echo "root:redhat123" | chpasswd

ADD config.yaml /etc/flightctl/
