# Base the image off of the official RHEL 9.6 bootc image
FROM registry.redhat.io/rhel9/rhel-bootc:9.7

# Install & Enable the Edge Manager Agent, disable (mask) the image mode update timer
RUN dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf clean all && \
    dnf -y install flightctl-agent-0:1.0.2-1.el9.x86_64 && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Install firewalld and enable at boot
RUN dnf install -y firewalld && \
    dnf clean all

# Copy early binding enrollment config.yaml into image
COPY config.yaml /etc/flightctl/config.yaml

# Disable selinux
RUN sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config

# DO NOT DO THIS IN PRODUCTION ENVIRONMENTS (for lab troubleshooting only)
RUN echo "root:redhat123" | chpasswd
