FROM registry.redhat.io/rhel9-eus/rhel-9.6-bootc:9.6

RUN dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo && \
    dnf -y clean all && \
    dnf -y install flightctl-agent-0:1.0.0~rc6-1.el9.x86_64 && \
    systemctl enable flightctl-agent.service && \
    systemctl mask bootc-fetch-apply-updates.timer

# Early-binding config
COPY config.yaml /etc/flightctl/config.yaml

# DO NOT DO THIS IN PRODUCTION ENVIRONMENTS (for lab troubleshooting only)
RUN echo "root:!redhat123" | chpasswd
