[customizations.installer.kickstart]
contents = """

# Unnatended install
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text --non-interactive
rootpw --lock
reboot

# leave free space on the "redhat" VG for the LVM Storate operator
zerombr
clearpart --all --initlabel
part /boot/efi --fstype=efi --size=200
part /boot --fstype=xfs --asprimary --size=800
part pv.01 --grow
volgroup rhel pv.01
logvol / --vgname=rhel --fstype=xfs --size=30720 --name=root

network --bootproto=dhcp --device=link --activate --onboot=on

%post --log=/var/log/anaconda/post-install.log --erroronfail

# Local user for console login and SSH (TESTING PURPOSES ONLY)
useradd -g wheel redhat
echo "redhat:redhat123" | chpasswd
mkdir /home/redhat/.ssh

# Ensure the directory exists regardless of image layer timing
mkdir -p /etc/crio

# Need a pull secret to download container images from whatever registries we need (for images are not embedded into the bootc image)
cat > /etc/crio/openshift-pull-secret <<EOF
{"auths":{"cloud.openshift.com":{"auth":"<snip>==","email":"kosborn@redhat.com"},"quay.io":{"auth":"<snip>","email":"kosborn@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTUyN2YzODNiLTkwMzEtNGU3NS04ZTM2LWVjMjM5MTUyNTg0NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTVOR1ZqTUdZeU1HVmxORGcwWTJJNE9EaGlPR0poWkRnNE1tWXdPVEF4TnlKOS5CeExSc2lvZjF5SVRCMTUyUlZCSTJtMU1GeWJHUnU3R0k3YllVVk5VOEpKVTlCRENsMjV3MTNNRm9VRFJNVmk1aF82Z2FKSGNZekt2VjNJUkl6MVBTaUZ1YW11MWFfTnVNZlZzNjhldmdIS1NkaTNmdGdwVE1ySkRjU19EdXFEM01yOERlMG83bGdPa1dYRU5RQm9wUV9QTnFxcl8tdUUyRDdaZTRNMVg1eGYwNjRMSGZ1Z1o3VGdJbFp1Vm1ZQmJaMUJFMlppNThqY2NBZWlfMGNsRkx2UUpRbnZ3NkxPRlFld2JSbjF4SUlXRVd5dW1YOHZlUFpzdU13WTBBRlNLZlBzdlgtZkJybWJkYmV2eFpwMFB0X2lIY3dkNDdnY05VVTlqOE9lRHd6TDVYLXk3SmdCalVrZnlLZGFMeS1KUDRmeVFDaldudDE1T204S3BtdThxd1ZvZExaMUFMQmxfdXNTMDIxVWtpSE1Yc05aWWZmaXhFczdrLUNSZUZvM0NxcGhIWkdzbFN1emR0VzI1a2dHTDdhb194U2JvWTUyRmt1eEhlbDBSd0NnTm5mQjhmU2tCTXhUVGZ6dTJBcENsVk9JbkpucHFfUjRwY05HejA1aFVQNkVubkI2TFAtdlUyZnNMbzZIaUxkd204SHlUOEJ3Z3hLa2p4c1JSa2tEa1hUUUdxVFRYTGpSc29jMmZ3RXNQRVJ2VHRReEY1WkZxOGJnWklyLTd2ZWh5RG14U3pvdDVTbXFRQWhjdGtIT2ZrX0FsbmVQU0dHd0tzVlhteU85Z2ZBTXBmaGZEVHRreU9JM0xTZVlYVUNXRWxUNlFUR1pELVRsRVIzRGFXWWpfTDhMZ3E1eXZmT25qTzE2OVVwUWNpQjE4MFl5WnpWaEwyLVBmVG5UYjlvYw==","email":"kosborn@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTUyN2YzODNiLTkwMzEtNGU3NS04ZTM2LWVjMjM5MTUyNTg0NDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTVOR1ZqTUdZeU1HVmxORGcwWTJJNE9EaGlPR0poWkRnNE1tWXdPVEF4TnlKOS5CeExSc2lvZjF5SVRCMTUyUlZCSTJtMU1GeWJHUnU3R0k3YllVVk5VOEpKVTlCRENsMjV3MTNNRm9VRFJNVmk1aF82Z2FKSGNZekt2VjNJUkl6MVBTaUZ1YW11MWFfTnVNZlZzNjhldmdIS1NkaTNmdGdwVE1ySkRjU19EdXFEM01yOERlMG83bGdPa1dYRU5RQm9wUV9QTnFxcl8tdUUyRDdaZTRNMVg1eGYwNjRMSGZ1Z1o3VGdJbFp1Vm1ZQmJaMUJFMlppNThqY2NBZWlfMGNsRkx2UUpRbnZ3NkxPRlFld2JSbjF4SUlXRVd5dW1YOHZlUFpzdU13WTBBRlNLZlBzdlgtZkJybWJkYmV2eFpwMFB0X2lIY3dkNDdnY05VVTlqOE9lRHd6TDVYLXk3SmdCalVrZnlLZGFMeS1KUDRmeVFDaldudDE1T204S3BtdThxd1ZvZExaMUFMQmxfdXNTMDIxVWtpSE1Yc05aWWZmaXhFczdrLUNSZUZvM0NxcGhIWkdzbFN1emR0VzI1a2dHTDdhb194U2JvWTUyRmt1eEhlbDBSd0NnTm5mQjhmU2tCTXhUVGZ6dTJBcENsVk9JbkpucHFfUjRwY05HejA1aFVQNkVubkI2TFAtdlUyZnNMbzZIaUxkd204SHlUOEJ3Z3hLa2p4c1JSa2tEa1hUUUdxVFRYTGpSc29jMmZ3RXNQRVJ2VHRReEY1WkZxOGJnWklyLTd2ZWh5RG14U3pvdDVTbXFRQWhjdGtIT2ZrX0FsbmVQU0dHd0tzVlhteU85Z2ZBTXBmaGZEVHRreU9JM0xTZVlYVUNXRWxUNlFUR1pELVRsRVIzRGFXWWpfTDhMZ3E1eXZmT25qTzE2OVVwUWNpQjE4MFl5WnpWaEwyLVBmVG5UYjlvYw==","email":"kosborn@redhat.com"}}}
EOF
chmod 600 /etc/crio/openshift-pull-secret

# Set a hostname, just for convenience
# echo "ushift" > /etc/hostname
# chmod 644 /etc/hostname

%end
"""

