[customizations.installer.kickstart]
contents = """

# Unnatended install
lang en_US.UTF-8
keyboard us
timezone Etc/UTC --utc
text --non-interactive
rootpw --lock
reboot

# leave free space on the "redhat" VG for the LVM Storate operator
zerombr
clearpart --all --initlabel
part /boot/efi --fstype=efi --size=200
part /boot --fstype=xfs --asprimary --size=800
part pv.01 --grow
volgroup rhel pv.01
logvol / --vgname=rhel --fstype=xfs --size=30720 --name=root

network --bootproto=dhcp --device=link --activate --onboot=on

%post --log=/var/log/anaconda/post-install.log --erroronfail

# Local user for console login and SSH (TESTING PURPOSES ONLY)
useradd -g wheel redhat
echo "redhat:redhat123" | chpasswd
mkdir /home/redhat/.ssh

# test

# Ensure the directory exists regardless of image layer timing
mkdir -p /etc/crio

# Need a pull secret to download container images from whatever registries we need (for images are not embedded into the bootc image)
cat > /etc/crio/openshift-pull-secret <<EOF
{"auths":{"cloud.openshift.com":{"auth":"<snip>==","email":"kosborn@redhat.com"},"quay.io":{"auth":"<snip>","email":"kosborn@redhat.com"},"registry.connect.redhat.com":{"auth":"<snip>","email":"kosborn@redhat.com"},"registry.redhat.io":{"auth":"<snip>","email":"kosborn@redhat.com"}}}
EOF
chmod 600 /etc/crio/openshift-pull-secret

# Set a hostname, just for convenience
# echo "ushift" > /etc/hostname
# chmod 644 /etc/hostname

%end
"""

